// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package account

import (
	"demo/internal/biz"
	"demo/internal/data"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeService(db *gorm.DB) *Service {
	dataDB := data.New(db)
	accountBiz := biz.New(dataDB)
	service := New(accountBiz)
	return service
}
