// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.1
// source: api/account/account.proto

package account

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// The request message containing the user's name.
type GetAccountByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAccountByIDRequest) Reset() {
	*x = GetAccountByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_account_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDRequest) ProtoMessage() {}

func (x *GetAccountByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIDRequest) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// The response message containing the greetings
type GetAccountByIDReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex     bool   `protobuf:"varint,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Age     int64  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Address string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetAccountByIDReply) Reset() {
	*x = GetAccountByIDReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_account_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountByIDReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIDReply) ProtoMessage() {}

func (x *GetAccountByIDReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_account_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIDReply.ProtoReflect.Descriptor instead.
func (*GetAccountByIDReply) Descriptor() ([]byte, []int) {
	return file_api_account_account_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountByIDReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetAccountByIDReply) GetSex() bool {
	if x != nil {
		return x.Sex
	}
	return false
}

func (x *GetAccountByIDReply) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *GetAccountByIDReply) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_api_account_account_proto protoreflect.FileDescriptor

var file_api_account_account_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x27, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67, 0x0a,
	0x13, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x62, 0x0a, 0x0e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x79, 0x49, 0x44, 0x12, 0x1e, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x64, 0x65,
	0x6d, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x3b, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_account_account_proto_rawDescOnce sync.Once
	file_api_account_account_proto_rawDescData = file_api_account_account_proto_rawDesc
)

func file_api_account_account_proto_rawDescGZIP() []byte {
	file_api_account_account_proto_rawDescOnce.Do(func() {
		file_api_account_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_account_account_proto_rawDescData)
	})
	return file_api_account_account_proto_rawDescData
}

var file_api_account_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_account_account_proto_goTypes = []interface{}{
	(*GetAccountByIDRequest)(nil), // 0: account.GetAccountByIDRequest
	(*GetAccountByIDReply)(nil),   // 1: account.GetAccountByIDReply
}
var file_api_account_account_proto_depIdxs = []int32{
	0, // 0: account.AccountService.GetAccountByID:input_type -> account.GetAccountByIDRequest
	1, // 1: account.AccountService.GetAccountByID:output_type -> account.GetAccountByIDReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_account_account_proto_init() }
func file_api_account_account_proto_init() {
	if File_api_account_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_account_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_account_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountByIDReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_account_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_account_account_proto_goTypes,
		DependencyIndexes: file_api_account_account_proto_depIdxs,
		MessageInfos:      file_api_account_account_proto_msgTypes,
	}.Build()
	File_api_account_account_proto = out.File
	file_api_account_account_proto_rawDesc = nil
	file_api_account_account_proto_goTypes = nil
	file_api_account_account_proto_depIdxs = nil
}
